### ISSUE TITLE
catmullRom没法用啊？

### ISSUE THREAD

**Issue by shenzhuomin** [tuia-fed/moto.js#26]
`import {curve} from '@tuia/moto.js'

curve.catmullRom({
  points: [
    {x: 50, y: 50},
    {x: 100, y: 150},
    {x: 200, y: 100},
    {x: 300, y: 50},
    {x: 350, y: 150}
  ]
}).start(v => console.log(v))`
什么都没打印出来，tween是能用的

**Comment by JetLua** [comment]
感谢反馈😊，确实是有问题。我尽快修复吧

**Comment by JetLua** [comment]
哦，似乎是少了`ticker.add(run)`。

https://github.com/tuia-fed/moto.js/blob/master/src/core/curve/bezier.js#L76

**Comment by shenzhuomin** [comment]
npm希望也尽快更新下哈
